# Generated by Django 6.0 on 2025-12-31 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('default_absence_threshold', models.IntegerField(default=40, help_text='Seuil par défaut appliqué aux nouveaux cours', verbose_name="Seuil d'absence par défaut (%)")),
                ('block_type', models.CharField(choices=[('ALERT_ONLY', 'Alerte uniquement'), ('EXAM_BLOCK', 'Blocage examen officiel')], default='EXAM_BLOCK', help_text='Comportement lorsque le seuil est dépassé', max_length=20, verbose_name='Type de blocage')),
                ('password_min_length', models.IntegerField(default=8, verbose_name='Longueur minimale du mot de passe')),
                ('password_require_uppercase', models.BooleanField(default=True, verbose_name='Exiger majuscules')),
                ('password_require_lowercase', models.BooleanField(default=True, verbose_name='Exiger minuscules')),
                ('password_require_numbers', models.BooleanField(default=True, verbose_name='Exiger chiffres')),
                ('password_require_special', models.BooleanField(default=False, verbose_name='Exiger caractères spéciaux')),
                ('mfa_enabled_globally', models.BooleanField(default=False, verbose_name='Authentification à deux facteurs (globale)')),
                ('data_retention_days', models.IntegerField(default=365, help_text='Durée de conservation des données personnelles', verbose_name='Rétention des données (jours)')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_settings', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramètres système',
                'verbose_name_plural': 'Paramètres système',
                'db_table': 'system_settings',
            },
        ),
    ]
