# Generated by Django 6.0 on 2026-02-11 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='systemsettings',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='system_settings_singleton_id_1'),
        ),
        migrations.AddConstraint(
            model_name='systemsettings',
            constraint=models.CheckConstraint(condition=models.Q(('default_absence_threshold__gte', 0), ('default_absence_threshold__lte', 100)), name='system_settings_default_threshold_range'),
        ),
        migrations.AddConstraint(
            model_name='systemsettings',
            constraint=models.CheckConstraint(condition=models.Q(('password_min_length__gte', 4), ('password_min_length__lte', 128)), name='system_settings_password_min_length_range'),
        ),
        migrations.AddConstraint(
            model_name='systemsettings',
            constraint=models.CheckConstraint(condition=models.Q(('data_retention_days__gte', 1), ('data_retention_days__lte', 3650)), name='system_settings_data_retention_days_range'),
        ),
    ]
