# Generated by Django 6.0 on 2026-03-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_systemsettings_system_settings_singleton_id_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="gps_latitude",
            field=models.FloatField(
                blank=True,
                help_text="Latitude GPS de l'établissement (ex: 36.7525)",
                null=True,
                verbose_name="Latitude de l'établissement",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="gps_longitude",
            field=models.FloatField(
                blank=True,
                help_text="Longitude GPS de l'établissement (ex: 3.0420)",
                null=True,
                verbose_name="Longitude de l'établissement",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="gps_radius_meters",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Distance maximale acceptée entre l'étudiant et l'établissement",
                verbose_name="Rayon de tolérance GPS (mètres)",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="qr_token_duration_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Le QR se régénère automatiquement après cette durée (défaut : 60s)",
                verbose_name="Durée de validité du QR (secondes)",
            ),
        ),
    ]
