# Generated by Django 6.0 on 2025-12-23 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '__first__'),
        ('enrollments', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id_absence', models.AutoField(primary_key=True, serialize=False)),
                ('type_absence', models.CharField(choices=[('HEURE', 'Heure'), ('SEANCE', 'Séance'), ('JOURNEE', 'Journée')], default='SEANCE', max_length=20)),
                ('duree_absence', models.FloatField(verbose_name='Durée (h)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('JUSTIFIEE', 'Justifiée'), ('NON_JUSTIFIEE', 'Non justifiée')], default='EN_ATTENTE', max_length=20)),
                ('encodee_par', models.ForeignKey(db_column='encodee_par', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Agent ayant encodé')),
                ('id_inscription', models.ForeignKey(db_column='id_inscription', on_delete=django.db.models.deletion.DO_NOTHING, to='enrollments.inscription', verbose_name='Inscription liée')),
                ('id_seance', models.ForeignKey(db_column='id_seance', on_delete=django.db.models.deletion.DO_NOTHING, to='academic_sessions.seance', verbose_name='Séance concernée')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'db_table': 'absence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id_justification', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.BinaryField(blank=True, null=True, verbose_name='Fichier (BLOB)')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire Étudiant')),
                ('commentaire_gestion', models.TextField(blank=True, null=True, verbose_name='Commentaire Gestion (Prof/Admin)')),
                ('validee', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('id_absence', models.OneToOneField(db_column='id_absence', on_delete=django.db.models.deletion.DO_NOTHING, to='absences.absence', verbose_name='Absence à justifier')),
                ('validee_par', models.ForeignKey(blank=True, db_column='validee_par', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Justification',
                'verbose_name_plural': 'Justifications',
                'db_table': 'justification',
                'managed': True,
            },
        ),
    ]
