# Generated by Django 6.0 on 2025-12-31 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absences', '0001_initial'),
        ('academic_sessions', '0002_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='encodee_par',
            field=models.ForeignKey(db_column='encodee_par', on_delete=django.db.models.deletion.PROTECT, related_name='absences_encodees', to=settings.AUTH_USER_MODEL, verbose_name='Agent ayant encodé'),
        ),
        migrations.AddField(
            model_name='absence',
            name='id_inscription',
            field=models.ForeignKey(db_column='id_inscription', on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='enrollments.inscription', verbose_name='Inscription liée'),
        ),
        migrations.AddField(
            model_name='absence',
            name='id_seance',
            field=models.ForeignKey(db_column='id_seance', on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='academic_sessions.seance', verbose_name='Séance concernée'),
        ),
        migrations.AddField(
            model_name='justification',
            name='id_absence',
            field=models.OneToOneField(db_column='id_absence', on_delete=django.db.models.deletion.PROTECT, related_name='justification', to='absences.absence', verbose_name='Absence à justifier'),
        ),
        migrations.AddField(
            model_name='justification',
            name='validee_par',
            field=models.ForeignKey(blank=True, db_column='validee_par', limit_choices_to={'role__in': ['SECRETAIRE', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['id_inscription', 'statut'], name='absence_id_insc_9eba9f_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['id_seance', 'statut'], name='absence_id_sean_f7ddea_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['statut', 'type_absence'], name='absence_statut_bd12b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('id_inscription', 'id_seance')},
        ),
        migrations.AddIndex(
            model_name='justification',
            index=models.Index(fields=['state', 'date_validation'], name='justificati_state_acfe9b_idx'),
        ),
        migrations.AddIndex(
            model_name='justification',
            index=models.Index(fields=['validee_par', 'state'], name='justificati_validee_fcba00_idx'),
        ),
    ]
