# Generated by Django 6.0 on 2025-12-25 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_justification_state'),
        ('academic_sessions', '0001_initial'),
        ('enrollments', '0003_alter_inscription_eligible_examen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'managed': True, 'ordering': ['-id_seance__date_seance', '-id_seance__heure_debut'], 'verbose_name': 'Absence', 'verbose_name_plural': 'Absences'},
        ),
        migrations.AlterModelOptions(
            name='justification',
            options={'managed': True, 'ordering': ['-date_validation', '-id_justification'], 'verbose_name': 'Justification', 'verbose_name_plural': 'Justifications'},
        ),
        migrations.AlterField(
            model_name='absence',
            name='duree_absence',
            field=models.FloatField(help_text="Durée de l'absence en heures", validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Durée (h)'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='encodee_par',
            field=models.ForeignKey(db_column='encodee_par', on_delete=django.db.models.deletion.PROTECT, related_name='absences_encodees', to=settings.AUTH_USER_MODEL, verbose_name='Agent ayant encodé'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='id_inscription',
            field=models.ForeignKey(db_column='id_inscription', on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='enrollments.inscription', verbose_name='Inscription liée'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='id_seance',
            field=models.ForeignKey(db_column='id_seance', on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='academic_sessions.seance', verbose_name='Séance concernée'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('JUSTIFIEE', 'Justifiée'), ('NON_JUSTIFIEE', 'Non justifiée')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='type_absence',
            field=models.CharField(choices=[('HEURE', 'Heure'), ('SEANCE', 'Séance'), ('JOURNEE', 'Journée')], db_index=True, default='SEANCE', max_length=20, verbose_name="Type d'absence"),
        ),
        migrations.AlterField(
            model_name='justification',
            name='commentaire',
            field=models.TextField(blank=True, help_text="Commentaire de l'étudiant expliquant l'absence", null=True, verbose_name='Commentaire Étudiant'),
        ),
        migrations.AlterField(
            model_name='justification',
            name='commentaire_gestion',
            field=models.TextField(blank=True, help_text='Commentaire interne du secrétariat', null=True, verbose_name='Commentaire Gestion'),
        ),
        migrations.AlterField(
            model_name='justification',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date et heure de validation/refus de la justification', null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='justification',
            name='document',
            field=models.BinaryField(blank=True, help_text='Document justificatif (PDF, image, etc.)', null=True, verbose_name='Fichier (BLOB)'),
        ),
        migrations.AlterField(
            model_name='justification',
            name='id_absence',
            field=models.OneToOneField(db_column='id_absence', on_delete=django.db.models.deletion.PROTECT, related_name='justification', to='absences.absence', verbose_name='Absence à justifier'),
        ),
        migrations.AlterField(
            model_name='justification',
            name='state',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='État de la demande'),
        ),
        migrations.AlterField(
            model_name='justification',
            name='validee',
            field=models.BooleanField(default=False, editable=False, help_text="DEPRECATED: Utiliser 'state' à la place. Conservé pour compatibilité."),
        ),
        migrations.AlterField(
            model_name='justification',
            name='validee_par',
            field=models.ForeignKey(blank=True, db_column='validee_par', limit_choices_to={'role__in': ['SECRETAIRE', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('id_inscription', 'id_seance')},
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['id_inscription', 'statut'], name='absence_id_insc_9eba9f_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['id_seance', 'statut'], name='absence_id_sean_f7ddea_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['statut', 'type_absence'], name='absence_statut_bd12b0_idx'),
        ),
        migrations.AddIndex(
            model_name='justification',
            index=models.Index(fields=['state', 'date_validation'], name='justificati_state_acfe9b_idx'),
        ),
        migrations.AddIndex(
            model_name='justification',
            index=models.Index(fields=['validee_par', 'state'], name='justificati_validee_fcba00_idx'),
        ),
    ]
