# Generated by Django 6.0 on 2026-03-01 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0007_remove_justification_validee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absence",
            name="duree_absence",
            field=models.FloatField(
                help_text="Durée de l'absence en heures",
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Durée (h)",
            ),
        ),
    ]
