# Generated by Django 6.0 on 2026-03-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0008_alter_absence_duree_absence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absence",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("JUSTIFIEE", "Justifiée"),
                    ("NON_JUSTIFIEE", "Non justifiée"),
                ],
                db_index=True,
                default="NON_JUSTIFIEE",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
