# Generated by Django 6.0 on 2026-03-07 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0009_fix_absence_default_statut_to_non_justifiee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="justification",
            name="commentaire",
            field=models.TextField(
                blank=True,
                help_text="Commentaire de l'étudiant expliquant l'absence",
                null=True,
                validators=[django.core.validators.MaxLengthValidator(2000)],
                verbose_name="Commentaire Étudiant",
            ),
        ),
        migrations.AlterField(
            model_name="justification",
            name="commentaire_gestion",
            field=models.TextField(
                blank=True,
                help_text="Commentaire interne du secrétariat",
                null=True,
                validators=[django.core.validators.MaxLengthValidator(2000)],
                verbose_name="Commentaire Gestion",
            ),
        ),
    ]
