# Generated by Django 6.0 on 2026-03-09 20:29

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def drop_trigger(apps, schema_editor):
    """Drop the trigger before altering the column type."""
    schema_editor.execute("DROP TRIGGER IF EXISTS trigger_verifier_seuil ON absence;")


def recreate_trigger(apps, schema_editor):
    """Recreate the trigger after altering the column type, updated for NUMERIC."""
    schema_editor.execute("""
        CREATE OR REPLACE FUNCTION public.verifier_seuil_absence()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $function$
        DECLARE
            id_insc INTEGER;
            total_absences NUMERIC;
            total_periodes INTEGER;
            seuil_pourcent INTEGER;
            seuil_heures NUMERIC;
        BEGIN
            IF TG_OP = 'DELETE' THEN
                id_insc := OLD.id_inscription;
            ELSE
                id_insc := NEW.id_inscription;
            END IF;

            SELECT COALESCE(SUM(a.duree_absence), 0)
            INTO total_absences
            FROM absence a
            JOIN inscription i ON a.id_inscription = i.id_inscription
            WHERE i.id_inscription = id_insc
            AND a.statut != 'JUSTIFIEE';

            SELECT c.nombre_total_periodes,
                   COALESCE(c.seuil_absence,
                            (SELECT COALESCE(s.default_absence_threshold, 40)
                             FROM system_settings s WHERE s.id = 1),
                            40)
            INTO total_periodes, seuil_pourcent
            FROM cours c
            JOIN inscription i ON c.id_cours = i.id_cours
            WHERE i.id_inscription = id_insc;

            seuil_heures := total_periodes * (seuil_pourcent / 100.0);

            UPDATE inscription
            SET eligible_examen = (total_absences <= seuil_heures)
            WHERE id_inscription = id_insc;

            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            ELSE
                RETURN NEW;
            END IF;
        END;
        $function$;
    """)
    schema_editor.execute("""
        CREATE TRIGGER trigger_verifier_seuil
        AFTER INSERT OR DELETE OR UPDATE OF duree_absence, statut
        ON public.absence
        FOR EACH ROW EXECUTE FUNCTION verifier_seuil_absence();
    """)


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0010_add_max_length_validators_to_justification_comments"),
        ("academic_sessions", "0007_seance_validation_fields"),
        ("enrollments", "0002_inscription_inscription_exemption_requires_motif"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="absence",
            name="absence_duree_absence_non_negative",
        ),
        # Drop trigger before column type change
        migrations.RunPython(drop_trigger, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="absence",
            name="duree_absence",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Durée de l'absence en heures",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Durée (h)",
            ),
        ),
        # Recreate trigger with NUMERIC types after column change
        migrations.RunPython(recreate_trigger, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="absence",
            constraint=models.CheckConstraint(
                condition=models.Q(("duree_absence__gte", 0.01)),
                name="absence_duree_absence_positive",
            ),
        ),
    ]
