# Generated by Django 6.0 on 2026-03-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0011_remove_absence_absence_duree_absence_non_negative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="note_professeur",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Remarque ajoutée par le professeur lors de l'enregistrement",
                max_length=500,
                verbose_name="Note du professeur",
            ),
        ),
    ]
