# Generated by Django 6.0 on 2026-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0012_add_note_professeur"),
    ]

    operations = [
        migrations.AddField(
            model_name="justification",
            name="date_soumission",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date et heure de soumission du justificatif par l'étudiant",
                null=True,
                verbose_name="Date de soumission",
            ),
        ),
    ]
