# Generated by Django 6.0 on 2026-03-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0014_qr_attendance_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrattendancetoken",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qrattendancetoken",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qrscanrecord",
            name="distance_meters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qrscanrecord",
            name="is_suspicious",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="qrscanrecord",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qrscanrecord",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
