# Generated by Django 6.0 on 2026-03-19 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0017_fix_type_absence_check_constraint"),
        ("academic_sessions", "0008_unique_seance_par_cours_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="qrattendancetoken",
            name="verify_location",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, la géolocalisation est obligatoire pour valider la présence.",
            ),
        ),
        migrations.CreateModel(
            name="QRScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("distance_meters", models.FloatField(blank=True, null=True)),
                (
                    "gps_status",
                    models.CharField(
                        choices=[
                            ("accepted", "GPS accepté"),
                            ("refused", "GPS refusé par l'étudiant"),
                            ("unavailable", "GPS indisponible"),
                            ("not_required", "Vérification non activée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scan_result",
                    models.CharField(
                        choices=[
                            ("validated", "Présence validée"),
                            ("rejected_gps", "Refusé — pas de GPS"),
                            ("rejected_distance", "Refusé — hors zone"),
                            ("rejected_expired", "Refusé — QR expiré"),
                            ("rejected_not_enrolled", "Refusé — non inscrit"),
                            ("rejected_duplicate", "Refusé — déjà scanné"),
                            ("rejected_locked", "Refusé — séance verrouillée"),
                            ("rejected_inactive", "Refusé — QR inactif"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "qr_token_used",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("user_agent", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_scan_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_scan_logs",
                        to="academic_sessions.seance",
                    ),
                ),
            ],
            options={
                "db_table": "qr_scan_log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
