# Generated by Django 6.0.2 on 2026-04-01 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0018_qr_gps_enforcement"),
        ("academic_sessions", "0008_unique_seance_par_cours_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="qrscanlog",
            index=models.Index(
                fields=["seance", "etudiant", "-timestamp"],
                name="qr_scan_log_seance__44cd42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="qrscanlog",
            index=models.Index(
                fields=["etudiant", "-timestamp"], name="qr_scan_log_etudian_bba61a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qrscanlog",
            index=models.Index(
                fields=["scan_result"], name="qr_scan_log_scan_re_7f486f_idx"
            ),
        ),
    ]
