# Generated by Django 6.0.2 on 2026-04-03 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absences", "0019_add_qrscanlog_indexes"),
        ("academic_sessions", "0008_unique_seance_par_cours_date"),
        ("enrollments", "0005_add_exemption_margin_validator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrscanlog",
            name="etudiant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qr_scan_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="qrscanlog",
            name="seance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qr_scan_logs",
                to="academic_sessions.seance",
            ),
        ),
        migrations.AlterField(
            model_name="qrscanrecord",
            name="inscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qr_scans",
                to="enrollments.inscription",
            ),
        ),
        migrations.AlterField(
            model_name="qrscanrecord",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qr_scans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
