# Generated by Django 6.0 on 2025-12-23 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '__first__'),
        ('academics', '0003_cours_prerequisites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id_inscription', models.AutoField(primary_key=True, serialize=False)),
                ('type_inscription', models.CharField(choices=[('NORMALE', 'Normale'), ('A_PART', 'À part')], default='NORMALE', max_length=20, verbose_name="Type d'inscription")),
                ('eligible_examen', models.BooleanField(default=True, verbose_name='Éligible examen ?')),
                ('status', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('NON_VALIDE', 'Non validé')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('id_annee', models.ForeignKey(db_column='id_annee', on_delete=django.db.models.deletion.DO_NOTHING, to='academic_sessions.anneeacademique', verbose_name='Année Académique')),
                ('id_cours', models.ForeignKey(db_column='id_cours', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.cours', verbose_name='Cours')),
                ('id_etudiant', models.ForeignKey(db_column='id_etudiant', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'inscription',
                'managed': True,
                'unique_together': {('id_etudiant', 'id_cours', 'id_annee')},
            },
        ),
    ]
