# Generated by Django 6.0 on 2025-12-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='exemption_40',
            field=models.BooleanField(default=False, verbose_name='Exemption 40%'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='motif_exemption',
            field=models.TextField(blank=True, null=True, verbose_name="Motif de l'exemption"),
        ),
    ]
