# Generated by Django 6.0 on 2026-03-09 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_sessions", "0007_seance_validation_fields"),
        ("academics", "0006_departement_departement_unique_nom_per_faculte"),
        ("enrollments", "0002_inscription_inscription_exemption_requires_motif"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["EN_COURS", "VALIDE", "NON_VALIDE"])
                ),
                name="inscription_status_valid_values",
            ),
        ),
        migrations.AddConstraint(
            model_name="inscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("type_inscription__in", ["NORMALE", "A_PART"])),
                name="inscription_type_valid_values",
            ),
        ),
    ]
