# Generated by Django 6.0 on 2025-12-25 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_cours_options_alter_departement_options_and_more'),
        ('enrollments', '0002_inscription_exemption_40_inscription_motif_exemption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='eligible_examen',
            field=models.BooleanField(db_index=True, default=True, help_text="Calculé automatiquement selon le taux d'absences. Ne pas modifier manuellement.", verbose_name='Éligible examen ?'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='exemption_40',
            field=models.BooleanField(default=False, help_text="Si activé, l'étudiant est exempté du seuil de 40% d'absences", verbose_name='Exemption 40%'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='id_annee',
            field=models.ForeignKey(db_column='id_annee', on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='academic_sessions.anneeacademique', verbose_name='Année Académique'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='id_cours',
            field=models.ForeignKey(db_column='id_cours', on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='academics.cours', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='id_etudiant',
            field=models.ForeignKey(db_column='id_etudiant', limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='motif_exemption',
            field=models.TextField(blank=True, help_text="Raison de l'exemption (obligatoire si exemption activée)", null=True, verbose_name="Motif de l'exemption"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('NON_VALIDE', 'Non validé')], db_index=True, default='EN_COURS', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='type_inscription',
            field=models.CharField(choices=[('NORMALE', 'Normale'), ('A_PART', 'À part')], db_index=True, default='NORMALE', max_length=20, verbose_name="Type d'inscription"),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['id_etudiant', 'id_annee', 'status'], name='inscription_id_etud_4e81d3_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['id_cours', 'id_annee', 'status'], name='inscription_id_cour_13bc0a_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['eligible_examen', 'status'], name='inscription_eligibl_219728_idx'),
        ),
    ]
