# Generated by Django 6.0 on 2026-03-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0003_inscription_inscription_status_valid_values_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="exemption_margin",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Points de pourcentage ajoutés au seuil quand l'étudiant est exempté. Ex: seuil=40%, marge=10% → bloqué à 50%.",
                verbose_name="Marge d'exemption (%)",
            ),
        ),
    ]
