# Generated by Django 6.0.2 on 2026-03-19 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0004_add_exemption_margin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="exemption_margin",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Points de pourcentage ajoutés au seuil quand l'étudiant est exempté. Ex: seuil=40%, marge=10% → bloqué à 50%.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Marge d'exemption (%)",
            ),
        ),
    ]
