# Generated by Django 6.0.2 on 2026-04-03 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_sessions", "0008_unique_seance_par_cours_date"),
        ("academics", "0006_departement_departement_unique_nom_per_faculte"),
        ("enrollments", "0005_add_exemption_margin_validator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exemption_margin__gte", 0), ("exemption_margin__lte", 100)
                ),
                name="inscription_exemption_margin_range",
            ),
        ),
    ]
