# Generated by Django 6.0 on 2025-12-31 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_utilisateur', models.AutoField(db_column='id_utilisateur', primary_key=True, serialize=False, verbose_name='ID Utilisateur')),
                ('nom', models.CharField(db_column='nom', max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(db_column='prenom', max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True, verbose_name='Adresse email')),
                ('mot_de_passe', models.CharField(db_column='mot_de_passe', max_length=255, verbose_name='Mot de passe hashé')),
                ('role', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PROFESSEUR', 'Professeur'), ('SECRETAIRE', 'Secrétaire'), ('ADMIN', 'Administrateur')], db_column='role', db_index=True, default='ETUDIANT', max_length=20, verbose_name='Rôle')),
                ('actif', models.BooleanField(db_column='actif', db_index=True, default=True, help_text='Désactiver un compte le masque sans le supprimer', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(db_column='date_creation', default=django.utils.timezone.now, verbose_name='Date de création')),
                ('must_change_password', models.BooleanField(db_column='must_change_password', db_index=True, default=False, help_text="Force l'utilisateur à changer son mot de passe à la prochaine connexion", verbose_name='Doit changer le mot de passe')),
                ('niveau', models.IntegerField(blank=True, choices=[(1, 'Année 1'), (2, 'Année 2'), (3, 'Année 3')], db_column='niveau', db_index=True, help_text="Niveau actuel de l'étudiant (1, 2 ou 3). Uniquement pour les étudiants.", null=True, verbose_name='Niveau académique')),
                ('last_login', models.DateTimeField(blank=True, help_text='Date et heure de la dernière connexion', null=True, verbose_name='Dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
                'ordering': ['nom', 'prenom'],
                'managed': True,
            },
        ),
    ]
