# Generated by Django 6.0 on 2025-12-20 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_utilisateur', models.AutoField(db_column='id_utilisateur', primary_key=True, serialize=False, verbose_name='ID Utilisateur')),
                ('nom', models.CharField(db_column='nom', max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(db_column='prenom', max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True, verbose_name='Adresse email')),
                ('mot_de_passe', models.CharField(db_column='mot_de_passe', max_length=255, verbose_name='Mot de passe hashé')),
                ('role', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PROFESSEUR', 'Professeur'), ('SECRETAIRE', 'Secrétaire'), ('ADMIN', 'Administrateur')], db_column='role', default='ETUDIANT', max_length=20, verbose_name='Rôle')),
                ('actif', models.BooleanField(db_column='actif', default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(db_column='date_creation', default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
                'ordering': ['nom', 'prenom'],
                'managed': False,
            },
        ),
    ]
