# Generated by Codex on 2026-01-25
from django.db import migrations, models


def set_role_flags(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='ADMIN').update(is_staff=True, is_superuser=True)
    User.objects.filter(role='SECRETAIRE').update(is_staff=True, is_superuser=False)
    User.objects.exclude(role__in=['ADMIN', 'SECRETAIRE']).update(is_staff=False, is_superuser=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(
                db_column='is_staff',
                default=False,
                db_index=True,
                help_text="Definit si l'utilisateur peut acceder a l'interface d'administration.",
                verbose_name='Staff',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(
                default=False,
                help_text='Indique que cet utilisateur a tous les droits sans restriction.',
                verbose_name='superuser status',
            ),
        ),
        migrations.RunPython(set_role_flags, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name='user',
                    old_name='mot_de_passe',
                    new_name='password',
                ),
                migrations.AlterField(
                    model_name='user',
                    name='password',
                    field=models.CharField(
                        db_column='mot_de_passe',
                        max_length=255,
                        verbose_name='Mot de passe hashe',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
