# Generated by Django 6.0 on 2025-12-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_last_login_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Date et heure de la dernière connexion', null=True, verbose_name='Dernière connexion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='actif',
            field=models.BooleanField(db_column='actif', db_index=True, default=True, help_text='Désactiver un compte le masque sans le supprimer', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PROFESSEUR', 'Professeur'), ('SECRETAIRE', 'Secrétaire'), ('ADMIN', 'Administrateur')], db_column='role', db_index=True, default='ETUDIANT', max_length=20, verbose_name='Rôle'),
        ),
    ]
