# Generated by Django 6.0 on 2025-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_last_login_alter_user_actif_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(db_column='must_change_password', db_index=True, default=False, help_text="Force l'utilisateur à changer son mot de passe à la prochaine connexion", verbose_name='Doit changer le mot de passe'),
        ),
    ]
