# Generated by Django 6.0 on 2025-12-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='niveau',
            field=models.IntegerField(blank=True, choices=[(1, 'Année 1'), (2, 'Année 2'), (3, 'Année 3')], db_column='niveau', db_index=True, help_text="Niveau actuel de l'étudiant (1, 2 ou 3). Uniquement pour les étudiants.", null=True, verbose_name='Niveau académique'),
        ),
    ]
