# Generated by Django 6.0.2 on 2026-04-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_usersession_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(
                db_column="two_factor_enabled",
                db_index=True,
                default=False,
                help_text="Indique si l'utilisateur a activé l'authentification à deux facteurs.",
                verbose_name="2FA activée",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_secret",
            field=models.CharField(
                blank=True,
                db_column="two_factor_secret",
                default="",
                help_text="Clé secrète Base32 partagée avec l'application d'authentification (Google Authenticator, Authy, etc.). Vide tant que la 2FA n'est pas activée.",
                max_length=32,
                verbose_name="Secret TOTP 2FA",
            ),
        ),
    ]
