# Generated by Django 6.0.2 on 2026-04-11 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_two_factor_enabled_user_two_factor_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorBackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="Hash Django (make_password). Le code en clair n'est jamais stocké.",
                        max_length=255,
                        verbose_name="Hash du code",
                    ),
                ),
                (
                    "used",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Utilisé"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'utilisation"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code de secours 2FA",
                "verbose_name_plural": "Codes de secours 2FA",
                "db_table": "two_factor_backup_code",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "used"], name="tfbc_user_used_idx")
                ],
            },
        ),
    ]
