# Generated by Django 6.0.4 on 2026-06-14 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_twofactorbackupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorbackupcode',
            name='code_hash',
            field=models.CharField(help_text="Hash Django (make_password / bcrypt). Le code en clair n'est jamais stocké.", max_length=255, verbose_name='Hash du code'),
        ),
        migrations.AlterField(
            model_name='twofactorbackupcode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Horodatage de la génération de ce code.', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='twofactorbackupcode',
            name='used',
            field=models.BooleanField(db_index=True, default=False, help_text='True si ce code a déjà été consommé et ne peut plus être réutilisé.', verbose_name='Utilisé'),
        ),
        migrations.AlterField(
            model_name='twofactorbackupcode',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de la première (et unique) utilisation de ce code.', null=True, verbose_name="Date d'utilisation"),
        ),
        migrations.AlterField(
            model_name='twofactorbackupcode',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur auquel appartient ce code de secours.', on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Horodatage de la connexion initiale.', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Adresse IP du client au moment de la connexion.', verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(help_text='Clé primaire de la session Django correspondante.', max_length=40, unique=True, verbose_name='Clé de session'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur propriétaire de cette session.', on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='En-tête HTTP User-Agent du navigateur client (tronqué à 500 car.).', verbose_name='User-Agent'),
        ),
    ]
