"""
FICHIER : apps/api/views/notification_viewset.py
RESPONSABILITE : ViewSet pour les notifications utilisateur (generees par le systeme).
"""
from drf_spectacular.utils import extend_schema, extend_schema_view
from rest_framework import mixins, viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from django.shortcuts import get_object_or_404

from apps.notifications.models import Notification

from ..pagination import StandardPagination
from ..serializers import NotificationSerializer


@extend_schema_view(
    list=extend_schema(summary="List my notifications", tags=["Notifications"]),
    mark_read=extend_schema(summary="Mark notification as read", tags=["Notifications"]),
    mark_all_read=extend_schema(summary="Mark all notifications as read", tags=["Notifications"]),
)
class NotificationViewSet(viewsets.GenericViewSet, mixins.ListModelMixin):
    """User notifications (auto-generated by the system)."""

    serializer_class = NotificationSerializer
    permission_classes = [IsAuthenticated]
    pagination_class = StandardPagination

    def get_queryset(self):
        if getattr(self, "swagger_fake_view", False):
            return Notification.objects.none()
        return Notification.objects.filter(
            id_utilisateur=self.request.user
        ).order_by("-date_envoi")

    @action(detail=True, methods=["post"])
    def mark_read(self, request, pk=None):
        notif = get_object_or_404(
            Notification, pk=pk, id_utilisateur=request.user
        )
        notif.lue = True
        notif.save(update_fields=["lue"])
        return Response({"status": "read"})

    @action(detail=False, methods=["post"])
    def mark_all_read(self, request):
        count = Notification.objects.filter(
            id_utilisateur=request.user, lue=False
        ).update(lue=True)
        return Response({"marked_read": count})
