# Generated by Django 6.0 on 2025-12-21 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('objet', models.CharField(default='Nouveau message', max_length=200, verbose_name='Objet')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(db_column='destinataire', on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_destinataire_set', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(db_column='expediteur', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
                'managed': True,
            },
        ),
    ]
