# Generated by Django 6.0 on 2025-12-25 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'managed': True, 'ordering': ['-date_envoi'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(blank=True, db_column='destinataire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(blank=True, db_column='expediteur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AlterField(
            model_name='message',
            name='lu',
            field=models.BooleanField(db_index=True, default=False, help_text='Indique si le message a été lu', verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='message',
            name='objet',
            field=models.CharField(db_index=True, default='Nouveau message', max_length=200, verbose_name='Objet'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['destinataire', 'lu', 'date_envoi'], name='message_destina_104ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expediteur', 'date_envoi'], name='message_expedit_affcce_idx'),
        ),
    ]
