# Generated by Django 6.0.2 on 2026-03-19 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="contenu",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(10000)],
                verbose_name="Message",
            ),
        ),
    ]
