# Generated by Django 6.0 on 2025-12-25 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAudit',
            fields=[
                ('id_log', models.AutoField(db_column='id_log', primary_key=True, serialize=False)),
                ('action', models.TextField(help_text="Description détaillée de l'action", verbose_name='Action effectuée')),
                ('date_action', models.DateTimeField(auto_now_add=True, db_column='date_action', db_index=True, verbose_name='Date et heure')),
                ('adresse_ip', models.GenericIPAddressField(db_column='adresse_ip', help_text="Adresse IP de l'utilisateur ayant effectué l'action", verbose_name='Adresse IP')),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITIQUE', 'Critique')], db_index=True, default='INFO', help_text="Niveau de criticité de l'action", max_length=20, verbose_name='Niveau')),
                ('objet_type', models.CharField(blank=True, choices=[('USER', 'Utilisateur'), ('COURS', 'Cours'), ('FACULTE', 'Faculté'), ('DEPARTEMENT', 'Département'), ('INSCRIPTION', 'Inscription'), ('ABSENCE', 'Absence'), ('JUSTIFICATION', 'Justification'), ('SYSTEM', 'Système'), ('AUTRE', 'Autre')], db_index=True, help_text="Type d'objet affecté par l'action", max_length=50, null=True, verbose_name="Type d'objet")),
                ('objet_id', models.IntegerField(blank=True, db_index=True, help_text="Identifiant de l'objet affecté", null=True, verbose_name="ID de l'objet")),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'db_table': 'log_audit',
                'ordering': ['-date_action'],
                'managed': True,
                'indexes': [models.Index(fields=['date_action', 'niveau'], name='log_audit_date_ac_6a5547_idx'), models.Index(fields=['objet_type', 'objet_id'], name='log_audit_objet_t_c41e87_idx'), models.Index(fields=['id_utilisateur', 'date_action'], name='log_audit_id_util_63b128_idx'), models.Index(fields=['niveau', 'date_action'], name='log_audit_niveau_b3dc05_idx')],
            },
        ),
    ]
