# Generated by Django 6.0 on 2025-12-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logaudit',
            name='niveau',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITIQUE', 'Critique')], db_index=True, default='INFO', help_text="Niveau de criticité de l'action", max_length=20, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='logaudit',
            name='objet_id',
            field=models.IntegerField(blank=True, db_index=True, help_text="Identifiant de l'objet affecté", null=True, verbose_name='ID de l\'objet'),
        ),
        migrations.AddField(
            model_name='logaudit',
            name='objet_type',
            field=models.CharField(blank=True, choices=[('USER', 'Utilisateur'), ('COURS', 'Cours'), ('FACULTE', 'Faculté'), ('DEPARTEMENT', 'Département'), ('INSCRIPTION', 'Inscription'), ('ABSENCE', 'Absence'), ('JUSTIFICATION', 'Justification'), ('SYSTEM', 'Système'), ('AUTRE', 'Autre')], db_index=True, help_text="Type d'objet affecté par l'action", max_length=50, null=True, verbose_name='Type d\'objet'),
        ),
        migrations.AddIndex(
            model_name='logaudit',
            index=models.Index(fields=['date_action', 'niveau'], name='log_audit_date_a_4a3942_idx'),
        ),
        migrations.AddIndex(
            model_name='logaudit',
            index=models.Index(fields=['objet_type', 'objet_id'], name='log_audit_objet_t_9826ec_idx'),
        ),
        migrations.AddIndex(
            model_name='logaudit',
            index=models.Index(fields=['id_utilisateur', 'date_action'], name='log_audit_id_uti_ff4bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='logaudit',
            index=models.Index(fields=['niveau', 'date_action'], name='log_audit_niveau_13bc0a_idx'),
        ),
    ]

