# Generated by Django 6.0 on 2026-03-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_postgres_trgm_logaudit_action_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logaudit",
            name="objet_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USER", "Utilisateur"),
                    ("COURS", "Cours"),
                    ("FACULTE", "Faculté"),
                    ("DEPARTEMENT", "Département"),
                    ("INSCRIPTION", "Inscription"),
                    ("ABSENCE", "Absence"),
                    ("JUSTIFICATION", "Justification"),
                    ("SEANCE", "Séance"),
                    ("EXPORT", "Export"),
                    ("SYSTEM", "Système"),
                    ("AUTRE", "Autre"),
                ],
                db_index=True,
                help_text="Type d'objet affecté par l'action",
                max_length=50,
                null=True,
                verbose_name="Type d'objet",
            ),
        ),
    ]
