# Generated by Django 6.0 on 2025-12-22 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id_departement', models.AutoField(primary_key=True, serialize=False)),
                ('nom_departement', models.CharField(max_length=200, verbose_name='Nom du département')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'departement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id_faculte', models.AutoField(primary_key=True, serialize=False)),
                ('nom_faculte', models.CharField(max_length=200, unique=True, verbose_name='Nom de la faculté')),
            ],
            options={
                'verbose_name': 'Faculté',
                'verbose_name_plural': 'Facultés',
                'db_table': 'faculte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
                ('code_cours', models.CharField(max_length=50, unique=True, verbose_name='Code du cours')),
                ('nom_cours', models.CharField(max_length=200, verbose_name='Intitulé du cours')),
                ('nombre_total_periodes', models.IntegerField(verbose_name='Total périodes (h)')),
                ('seuil_absence', models.IntegerField(blank=True, default=40, null=True, verbose_name="Seuil d'absence (%)")),
                ('id_departement', models.ForeignKey(db_column='id_departement', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'db_table': 'cours',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='id_faculte',
            field=models.ForeignKey(db_column='id_faculte', on_delete=django.db.models.deletion.DO_NOTHING, to='academics.faculte', verbose_name='Faculté de rattachement'),
        ),
    ]
