# Generated by Django 6.0 on 2025-12-31 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='professeur',
            field=models.ForeignKey(blank=True, db_column='id_professeur', limit_choices_to={'role': 'PROFESSEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL, verbose_name='Professeur responsable'),
        ),
        migrations.AddField(
            model_name='cours',
            name='id_departement',
            field=models.ForeignKey(db_column='id_departement', on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='academics.departement', verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='departement',
            name='id_faculte',
            field=models.ForeignKey(db_column='id_faculte', on_delete=django.db.models.deletion.PROTECT, related_name='departements', to='academics.faculte', verbose_name='Faculté de rattachement'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['id_departement', 'actif'], name='cours_id_depa_4a3942_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['professeur', 'actif'], name='cours_id_prof_ff4bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['id_annee', 'actif'], name='cours_id_anne_78748e_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['niveau', 'actif'], name='cours_niveau_ea1142_idx'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['id_faculte', 'actif'], name='departement_id_facu_9826ec_idx'),
        ),
    ]
