# Generated by Django 6.0 on 2026-02-11 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_cours_required_fields(apps, schema_editor):
    Cours = apps.get_model('academics', 'Cours')
    AnneeAcademique = apps.get_model('academic_sessions', 'AnneeAcademique')
    Inscription = apps.get_model('enrollments', 'Inscription')
    db_alias = schema_editor.connection.alias

    # 1) Backfill id_annee from enrollments when unambiguous.
    for cours in Cours.objects.using(db_alias).filter(id_annee__isnull=True).only('id_cours'):
        year_ids = list(
            Inscription.objects.using(db_alias)
            .filter(id_cours_id=cours.id_cours)
            .exclude(id_annee_id__isnull=True)
            .values_list('id_annee_id', flat=True)
            .distinct()
        )
        if len(year_ids) == 1:
            Cours.objects.using(db_alias).filter(id_cours=cours.id_cours).update(id_annee_id=year_ids[0])

    # 2) Remaining id_annee can use the active year if there is exactly one.
    missing_year_qs = Cours.objects.using(db_alias).filter(id_annee__isnull=True)
    if missing_year_qs.exists():
        active_year_ids = list(
            AnneeAcademique.objects.using(db_alias)
            .filter(active=True)
            .values_list('id_annee', flat=True)
        )
        if len(active_year_ids) == 1:
            missing_year_qs.update(id_annee_id=active_year_ids[0])

    # 3) Backfill niveau from enrolled students when unambiguous.
    for cours in Cours.objects.using(db_alias).filter(niveau__isnull=True).only('id_cours'):
        niveaux = list(
            Inscription.objects.using(db_alias)
            .filter(id_cours_id=cours.id_cours)
            .exclude(id_etudiant__niveau__isnull=True)
            .values_list('id_etudiant__niveau', flat=True)
            .distinct()
        )
        if len(niveaux) == 1 and niveaux[0] in (1, 2, 3):
            Cours.objects.using(db_alias).filter(id_cours=cours.id_cours).update(niveau=niveaux[0])

    unresolved_year = list(
        Cours.objects.using(db_alias)
        .filter(id_annee__isnull=True)
        .values_list('id_cours', 'code_cours')[:10]
    )
    if unresolved_year:
        raise RuntimeError(
            'Cannot set cours.id_annee to NOT NULL. '
            f'Courses still missing id_annee (first 10): {unresolved_year}'
        )

    unresolved_level = list(
        Cours.objects.using(db_alias)
        .filter(niveau__isnull=True)
        .values_list('id_cours', 'code_cours')[:10]
    )
    if unresolved_level:
        raise RuntimeError(
            'Cannot set cours.niveau to NOT NULL. '
            f'Courses still missing niveau (first 10): {unresolved_level}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0004_seance_seance_heure_fin_after_debut'),
        ('academics', '0002_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_cours_required_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cours',
            name='id_annee',
            field=models.ForeignKey(
                db_column='id_annee',
                help_text='Ann\u00e9e acad\u00e9mique \u00e0 laquelle ce cours appartient (assign\u00e9e automatiquement)',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='cours',
                to='academic_sessions.anneeacademique',
                verbose_name='Ann\u00e9e Acad\u00e9mique',
            ),
        ),
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.IntegerField(
                choices=[(1, 'Ann\u00e9e 1'), (2, 'Ann\u00e9e 2'), (3, 'Ann\u00e9e 3')],
                db_index=True,
                help_text='Niveau du cours (1, 2 ou 3). D\u00e9termine les pr\u00e9requis autoris\u00e9s.',
                verbose_name="Niveau d'\u00e9tude",
            ),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.CheckConstraint(
                condition=models.Q(('nombre_total_periodes__gte', 1), ('nombre_total_periodes__lte', 1000)),
                name='cours_nombre_total_periodes_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('seuil_absence__isnull', True),
                    models.Q(('seuil_absence__gte', 0), ('seuil_absence__lte', 100)),
                    _connector='OR',
                ),
                name='cours_seuil_absence_range_or_null',
            ),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.CheckConstraint(
                condition=models.Q(('niveau__in', [1, 2, 3])),
                name='cours_niveau_allowed_values',
            ),
        ),
    ]

