# Generated by Django 6.0 on 2025-12-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_cours_professeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='academics.cours', verbose_name='Prérequis'),
        ),
    ]
