# Generated by Django 6.0 on 2025-12-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_cours_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='departement',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='faculte',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
