# Generated by Django 6.0 on 2025-12-25 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_cours_actif_departement_actif_faculte_actif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'managed': True, 'ordering': ['code_cours'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'managed': True, 'ordering': ['id_faculte__nom_faculte', 'nom_departement'], 'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterModelOptions(
            name='faculte',
            options={'managed': True, 'ordering': ['nom_faculte'], 'verbose_name': 'Faculté', 'verbose_name_plural': 'Facultés'},
        ),
        migrations.AlterField(
            model_name='cours',
            name='actif',
            field=models.BooleanField(db_index=True, default=True, help_text='Désactiver un cours le masque sans le supprimer', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='code_cours',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code du cours'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='id_departement',
            field=models.ForeignKey(db_column='id_departement', on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='academics.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='nombre_total_periodes',
            field=models.IntegerField(help_text="Nombre total d'heures de cours", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Total périodes (h)'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text="Cours qui doivent être validés avant de s'inscrire à ce cours", related_name='required_by', to='academics.cours', verbose_name='Prérequis'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='professeur',
            field=models.ForeignKey(blank=True, db_column='id_professeur', limit_choices_to={'role': 'PROFESSEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL, verbose_name='Professeur responsable'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='seuil_absence',
            field=models.IntegerField(blank=True, default=None, help_text='Seuil personnalisé pour ce cours. Si vide, utilise le seuil par défaut du système.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Seuil d'absence (%)"),
        ),
        migrations.AlterField(
            model_name='departement',
            name='actif',
            field=models.BooleanField(db_index=True, default=True, help_text='Désactiver un département le masque sans le supprimer', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='id_faculte',
            field=models.ForeignKey(db_column='id_faculte', on_delete=django.db.models.deletion.PROTECT, related_name='departements', to='academics.faculte', verbose_name='Faculté de rattachement'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom_departement',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nom du département'),
        ),
        migrations.AlterField(
            model_name='faculte',
            name='actif',
            field=models.BooleanField(db_index=True, default=True, help_text='Désactiver une faculté la masque sans la supprimer', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='faculte',
            name='nom_faculte',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Nom de la faculté'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['id_departement', 'actif'], name='cours_id_depa_4a3942_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['professeur', 'actif'], name='cours_id_prof_ff4bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['id_faculte', 'actif'], name='departement_id_facu_9826ec_idx'),
        ),
    ]
