# Generated by Django 6.0 on 2026-03-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_cours_active_partial_index_concurrently"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="departement",
            constraint=models.UniqueConstraint(
                fields=("nom_departement", "id_faculte"),
                name="departement_unique_nom_per_faculte",
            ),
        ),
    ]
