# Generated by Django 6.0 on 2025-12-27 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0002_rename_seance_id_cou_4a3942_idx_seance_id_cour_9b1f9e_idx_and_more'),
        ('academics', '0005_alter_cours_options_alter_departement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='id_annee',
            field=models.ForeignKey(blank=True, db_column='id_annee', help_text='Année académique à laquelle ce cours appartient', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='academic_sessions.anneeacademique', verbose_name='Année Académique'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['id_annee', 'actif'], name='cours_id_anne_78748e_idx'),
        ),
    ]
