# Generated by Django 6.0 on 2025-12-27 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0002_rename_seance_id_cou_4a3942_idx_seance_id_cour_9b1f9e_idx_and_more'),
        ('academics', '0006_add_annee_to_cours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.IntegerField(blank=True, choices=[(1, 'Année 1'), (2, 'Année 2'), (3, 'Année 3')], db_index=True, help_text='Niveau du cours (1, 2 ou 3). Détermine les prérequis autorisés.', null=True, verbose_name="Niveau d'étude"),
        ),
        migrations.AlterField(
            model_name='cours',
            name='id_annee',
            field=models.ForeignKey(blank=True, db_column='id_annee', help_text='Année académique à laquelle ce cours appartient (assignée automatiquement)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='academic_sessions.anneeacademique', verbose_name='Année Académique'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['niveau', 'actif'], name='cours_niveau_ea1142_idx'),
        ),
    ]
