# Generated by Django 6.0 on 2025-12-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seance',
            new_name='seance_id_cour_9b1f9e_idx',
            old_name='seance_id_cou_4a3942_idx',
        ),
        migrations.RenameIndex(
            model_name='seance',
            new_name='seance_id_anne_0f93f7_idx',
            old_name='seance_id_ann_9826ec_idx',
        ),
    ]
