# Generated by Django 6.0 on 2026-02-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0003_seance_unique'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='seance_heure_fin_after_debut'),
        ),
    ]
