# Generated by Django 6.0 on 2026-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0004_seance_seance_heure_fin_after_debut'),
        ('academics', '0003_alter_cours_id_annee_alter_cours_niveau_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['id_cours', 'id_annee', 'date_seance'], name='seance_id_cour_e986d8_idx'),
        ),
    ]
