# Generated by Django 6.0 on 2026-03-06 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_sessions", "0006_seance_index_rationalization_concurrently"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="seance",
            name="date_validated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de validation"
            ),
        ),
        migrations.AddField(
            model_name="seance",
            name="validated",
            field=models.BooleanField(
                default=False,
                help_text="Une fois validée, la présence ne peut plus être modifiée par le professeur.",
                verbose_name="Séance validée",
            ),
        ),
        migrations.AddField(
            model_name="seance",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seances_validees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validée par",
            ),
        ),
    ]
