# Generated by Django 6.0 on 2026-03-18 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_sessions", "0007_seance_validation_fields"),
        ("academics", "0006_departement_departement_unique_nom_per_faculte"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="seance",
            name="unique_seance_per_course_time",
        ),
        migrations.AddConstraint(
            model_name="seance",
            constraint=models.UniqueConstraint(
                fields=("id_cours", "date_seance"), name="unique_seance_par_cours_date"
            ),
        ),
    ]
