name: Bug report
description: Report a reproducible bug
title: "bug(<scope>): <short description>"
labels: ["bugfix"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide enough detail to reproduce and verify the fix.
  - type: input
    id: scope
    attributes:
      label: Scope
      description: Module or area impacted (dashboard, absences, ci, etc.)
      placeholder: dashboard
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is happening?
      placeholder: Short and clear bug description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen instead?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / traceback
      description: Paste relevant logs or traceback
      render: shell
  - type: textarea
    id: done
    attributes:
      label: Done checklist
      value: |
        - [ ] I verified this is still reproducible on `Dev`
        - [ ] I included enough details for reproduction
    validations:
      required: false
