"""
UniAbsences – scripts.setup.setup_test_data_justif
====================================================

Extends the V1 dataset (created by ``setup_test_data.py``) by adding a
pending justification for the student's first absence record.

What this script does
---------------------
1. Retrieves the student ``alex.student@uni.edu`` and their first enrollment.
2. Finds the first absence on that enrollment.
3. Creates a ``Justification`` object with ``validee=False`` (pending review)
   and updates the corresponding absence status to ``EN_ATTENTE``.

Prerequisites
-------------
``setup_test_data.py`` must have been run first so that the student,
enrollment, and absence records exist.

Usage
-----
::

    python scripts/setup/setup_test_data_justif.py

Part of: UniAbsences setup / test-data seeding layer (v1 – justification add-on).
"""

import os
import sys
from pathlib import Path

# Bootstrap Django before any app imports.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(BASE_DIR))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')

import django
django.setup()

from apps.accounts.models import User
from apps.enrollments.models import Inscription
from apps.absences.models import Absence, Justification


def create_justification() -> None:
    """Attach a pending justification to the student's first absence.

    Looks up the student's enrollment and first absence record.  If no
    justification already exists for that absence, creates one with a dummy
    document payload and sets the absence status to ``'EN_ATTENTE'``.
    """
    print("Adding Pending Justification...")

    student = User.objects.get(email="alex.student@uni.edu")
    inscription = Inscription.objects.filter(id_etudiant=student).first()

    if not inscription:
        print("No inscription found for student!")
        return

    # Grab the very first absence recorded for this enrollment.
    absence = Absence.objects.filter(id_inscription=inscription).first()

    if absence:
        # Only create the justification if one does not already exist.
        if not hasattr(absence, 'justification'):
            justification = Justification.objects.create(
                id_absence=absence,
                commentaire="Maladie (Generated by Script)",
                validee=False,
                document=b"dummy_content"  # Placeholder binary for the file field
            )
            # Update the absence status to reflect the pending justification.
            absence.statut = 'EN_ATTENTE'
            absence.save()
            print(f"Created Justification for Absence {absence.id_absence}")
        else:
            print("Justification already exists.")

    else:
        print("No absences found to justify.")


if __name__ == "__main__":
    create_justification()
