import os
import sys
from pathlib import Path
# Ajouter le répertoire racine au PYTHONPATH
BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(BASE_DIR))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')

import django
django.setup()
# Setup Django environment
from apps.accounts.models import User
from apps.enrollments.models import Inscription
from apps.absences.models import Absence, Justification
from django.db import transaction

def create_justification():
    print("Adding Pending Justification...")
    
    student = User.objects.get(email="alex.student@uni.edu")
    inscription = Inscription.objects.filter(id_etudiant=student).first()
    
    if not inscription:
        print("No inscription found for student!")
        return

    # Get one absence
    absence = Absence.objects.filter(id_inscription=inscription).first()
    
    if absence:
        # Check if justification exists
        if not hasattr(absence, 'justification'):
            justification = Justification.objects.create(
                id_absence=absence,
                commentaire="Maladie (Generated by Script)",
                validee=False,
                document=b"dummy_content"
            )
            absence.statut = 'EN_ATTENTE'
            absence.save()
            print(f"Created Justification for Absence {absence.id_absence}")
        else:
            print("Justification already exists.")
            
        # Ensure at least one other absence is non-justified so we see the progress bar effect
        # We already created 40h in the previous run.
            
    else:
        print("No absences found to justify.")

if __name__ == "__main__":
    create_justification()
")

if __name__ == "__main__":
    create_justification()
