"""
UniAbsences – scripts.maintenance.create_system_settings_table
==============================================================

Idempotent DDL script that creates the ``system_settings`` table directly
via raw SQL when the corresponding Django migration cannot be applied through
the normal ``python manage.py migrate`` workflow.

Typical scenario
----------------
When the ``system_settings`` migration has been *faked* (i.e. recorded in
``django_migrations`` without actually executing the DDL), the physical
table is missing from the database.  Running this script after the fake
creates the table so that the application can start normally.

The entire DDL block uses ``IF NOT EXISTS`` guards, making the script safe
to run multiple times without raising errors.

Usage
-----
After faking the migration, run::

    python scripts/maintenance/create_system_settings_table.py

This script targets PostgreSQL (uses ``GENERATED BY DEFAULT AS IDENTITY``
and a PL/pgSQL ``DO $$ ... $$`` block for the foreign key constraint).

Part of: UniAbsences maintenance / schema repair layer.
"""

import os
import sys
from pathlib import Path

# Bootstrap Django before using its database connection.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(BASE_DIR))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')

import django
django.setup()

from django.db import connection

# ---------------------------------------------------------------------------
# DDL statement
# ---------------------------------------------------------------------------

# The SQL block creates the table, an index on the FK column, and a named
# foreign key constraint referencing the ``utilisateur`` table.
# All three statements are guarded by ``IF NOT EXISTS`` / PL/pgSQL checks so
# that partial previous runs do not cause failures.
sql = """
CREATE TABLE IF NOT EXISTS "system_settings" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "default_absence_threshold" integer NOT NULL,
    "block_type" varchar(20) NOT NULL,
    "password_min_length" integer NOT NULL,
    "password_require_uppercase" boolean NOT NULL,
    "password_require_lowercase" boolean NOT NULL,
    "password_require_numbers" boolean NOT NULL,
    "password_require_special" boolean NOT NULL,
    "mfa_enabled_globally" boolean NOT NULL,
    "data_retention_days" integer NOT NULL,
    "last_modified" timestamp with time zone NOT NULL,
    "modified_by_id" integer NULL
);

-- Create index on the FK column if it does not already exist.
CREATE INDEX IF NOT EXISTS "system_settings_modified_by_id_d3ec84b4" ON "system_settings" ("modified_by_id");

-- Add the named FK constraint only if it is not yet present, using a
-- PL/pgSQL anonymous block to check pg_constraint first.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'system_settings_modified_by_id_d3ec84b4_fk_utilisate'
    ) THEN
        ALTER TABLE "system_settings"
        ADD CONSTRAINT "system_settings_modified_by_id_d3ec84b4_fk_utilisate"
        FOREIGN KEY ("modified_by_id")
        REFERENCES "utilisateur" ("id_utilisateur")
        DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
"""

# ---------------------------------------------------------------------------
# Execute
# ---------------------------------------------------------------------------

with connection.cursor() as cursor:
    cursor.execute(sql)
    print("SystemSettings table created successfully!")
