import os
import sys
from pathlib import Path
# Ajouter le répertoire racine au PYTHONPATH
BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(BASE_DIR))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')

import django
django.setup()
#!/usr/bin/env python
"""
Script to create the system_settings table if it doesn't exist.
Run this after faking the migration.
"""

from django.db import connection

sql = """
CREATE TABLE IF NOT EXISTS "system_settings" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "default_absence_threshold" integer NOT NULL,
    "block_type" varchar(20) NOT NULL,
    "password_min_length" integer NOT NULL,
    "password_require_uppercase" boolean NOT NULL,
    "password_require_lowercase" boolean NOT NULL,
    "password_require_numbers" boolean NOT NULL,
    "password_require_special" boolean NOT NULL,
    "mfa_enabled_globally" boolean NOT NULL,
    "data_retention_days" integer NOT NULL,
    "last_modified" timestamp with time zone NOT NULL,
    "modified_by_id" integer NULL
);

-- Create index if it doesn't exist
CREATE INDEX IF NOT EXISTS "system_settings_modified_by_id_d3ec84b4" ON "system_settings" ("modified_by_id");

-- Add foreign key constraint if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'system_settings_modified_by_id_d3ec84b4_fk_utilisate'
    ) THEN
        ALTER TABLE "system_settings" 
        ADD CONSTRAINT "system_settings_modified_by_id_d3ec84b4_fk_utilisate" 
        FOREIGN KEY ("modified_by_id") 
        REFERENCES "utilisateur" ("id_utilisateur") 
        DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
"""

with connection.cursor() as cursor:
    cursor.execute(sql)
    print("SystemSettings table created successfully!")


    print("SystemSettings table created successfully!")

