# Generated by Django 6.0 on 2025-12-31 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(db_column='id_notification', primary_key=True, serialize=False)),
                ('message', models.TextField(db_column='message', help_text='Contenu de la notification', verbose_name='Message')),
                ('type', models.CharField(blank=True, choices=[('INTERNE', 'Interne'), ('ALERTE', 'Alerte'), ('INFO', 'Information')], db_column='type', db_index=True, max_length=20, null=True, verbose_name='Type')),
                ('lue', models.BooleanField(db_column='lue', db_index=True, default=False, help_text='Indique si la notification a été lue', verbose_name='Lu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, db_column='date_envoi', db_index=True, verbose_name="Date d'envoi")),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-date_envoi', '-id_notification'],
                'managed': True,
                'indexes': [models.Index(fields=['id_utilisateur', 'lue', 'date_envoi'], name='notificatio_id_util_7c5af1_idx'), models.Index(fields=['type', 'date_envoi'], name='notificatio_type_9f2480_idx')],
            },
        ),
    ]
