# Generated by Django 6.0 on 2026-03-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_update_notification_type_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("INTERNE", "Interne"),
                    ("ALERTE", "Alerte"),
                    ("INFO", "Information"),
                ],
                db_column="type",
                db_index=True,
                default="INFO",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
