# Generated by Django 6.0.2 on 2026-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(db_index=True, max_length=64, unique=True)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("event_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "email_log",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="email_log_created_d2a0e7_idx"
                    )
                ],
            },
        ),
    ]
