# Generated by Django 6.0.2 on 2026-03-19 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_emaillog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(
                db_column="message",
                help_text="Contenu de la notification",
                validators=[django.core.validators.MaxLengthValidator(5000)],
                verbose_name="Message",
            ),
        ),
    ]
