# Generated by Django 6.0.4 on 2026-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_textfield_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
