# Generated by Django 6.0.4 on 2026-10-06 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_textfield_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnvoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire_email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('statut', models.CharField(choices=[('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec')], db_index=True, max_length=10, verbose_name='Statut')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'envoi")),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'E-mail envoyé',
                'verbose_name_plural': 'E-mails envoyés',
                'db_table': 'email_envoi',
                'ordering': ['-date_envoi', '-id'],
                'managed': True,
                'indexes': [models.Index(fields=['destinataire', 'date_envoi'], name='email_envoi_destina_fb30e4_idx')],
            },
        ),
    ]
